/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Notify: typeof import('./src/components/Notify/index.vue')['default']
    NotifyList: typeof import('./src/components/Notify/NotifyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/index.vue')['default']
    SearchFooter: typeof import('./src/components/SearchMenu/SearchFooter.vue')['default']
    SearchMenu: typeof import('./src/components/SearchMenu/index.vue')['default']
    SearchModal: typeof import('./src/components/SearchMenu/SearchModal.vue')['default']
    SearchResult: typeof import('./src/components/SearchMenu/SearchResult.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch/index.vue')['default']
  }
}
